package com.gpis.marketplace_link.enums;


public enum EmailType {
    GENERIC,
    EMAIL_CONFIRMATION,
    PASSWORD_RESET,
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_UPDATE,
    APPOINTMENT_REMINDER_24H,
    PUBLICATION_BLOCKED_NOTIFICATION
}
