package com.gpis.marketplace_link.enums;


public enum EmailType {
    GENERIC,
    EMAIL_CONFIRMATION,
    PASSWORD_RESET,

    MODERATOR_ACCOUNT_CREATED,
    APPEAL_SELLER_MODERATOR_ASSIGNED_NOTIFICATION,

    PUBLICATION_BLOCKED_NOTIFICATION,
    PUBLICATION_UNLOCK_NOTIFICATION,
    PUBLICATION_APPEAL_AVAILABLE_NOTIFICATION,
    APPEAL_RECEIVED_CONFIRMATION_NOTIFICATION,

    APPEAL_SUBMISSION_NOTIFICATION,
    MODERATOR_NEW_APPEAL_ASSIGNED_NOTIFICATION,
    APPEAL_ASSIGNED_TO_MODERATOR_NOTIFICATION,

    APPEAL_APPROVED_NOTIFICATION,
    APPEAL_REJECTED_NOTIFICATION,
    APPEAL_PENDING_ASSIGNMENT_NOTIFICATION,
    APPEAL_AUTO_ASSIGNED_NOTIFICATION,
    NEW_APPEAL_ASSIGNED_TO_MODERATOR_NOTIFICATION,

    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_UPDATE,
    APPOINTMENT_REMINDER_24H
}
